# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d853885043ef61d8c91973889f944de01da15a4eb2309389acb6d05aec87cbc46ac6c5e10c937fd7b85e6699b68d13add405bdd2ddef54b95eaebe5b32e4c28c

test:
  secret_key_base: e6c1f3629b156de1b845605521c65c20baa0ac2a40d0db2ad7909bdae4550f4fedf05c0f971537a79be6dd47c6ec1cce920b8af8ac673925848a81770529f901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
